// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CamVidMaskImage

//
Texture2D<float4> SourceImage;
// The pixel data for the input image
Texture2D<float4> MaskTexture;
// The pixel data for the processed image
RWTexture2D<float4> Result;

float maskWeight;


 //Apply the ImageNet normalization stats from PyTorch to an image
[numthreads(8, 8, 1)]
void CamVidMaskImage(uint3 id : SV_DispatchThreadID)
{
    float3 colors[32] =
    {
        // Animal
        float3(186.0f, 85.0f, 211.0f),
        // Archway
        float3(75.0f, 0.0f, 130.0f),
        // Bicyclist
        float3(0.0f, 0.0f, 0.0f),
        // Bridge
        float3(238.0f, 232.0f, 170.0f),
        // Building
        float3(255.0f, 69.0f, 0.0f),
        // Car
        float3(165.0f, 42.0f, 42.0f),
        // CartLuggagePram
        float3(0.0f, 0.0f, 255.0f),
        // Child
        float3(0.0f, 0.0f, 139.0f),
        // Column_Pole
        float3(240.0f, 255.0f, 255.0f),
        // Fence
        float3(240.0f, 128.0f, 128.0f),
        // LaneMkgsDriv
        float3(255.0f, 182.0f, 193.0f),
        // LaneMkgsNonDriv
        float3(0.0f, 0.0f, 128.0f),
        // Misc_Text
        float3(245.0f, 222.0f, 179.0f),
        // MotorcycleScooter
        float3(127.0f, 255.0f, 212.0f),
        // OtherMoving
        float3(25.0f, 25.0f, 112.0f),
        // ParkingBlock
        float3(188.0f, 143.0f, 143.0f),
        // Pedestrian
        float3(255.0f, 105.0f, 180.0f),
        // Road
        float3(255.0f, 250.0f, 250.0f),
        // RoadShoulder
        float3(255.0f, 218.0f, 185.0f),
        // Sidewalk
        float3(123.0f, 104.0f, 238.0f),
        // SignSymbol
        float3(255.0f, 0.0f, 0.0f),
        // Sky
        float3(248.0f, 248.0f, 255.0f),
        // SUVPickupTruck
        float3(95.0f, 158.0f, 160.0f),
        // TrafficCone
        float3(255.0f, 160.0f, 122.0f),
        // TrafficLight
        float3(128.0f, 128.0f, 128.0f),
        // Train
        float3(143.0f, 188.0f, 143.0f),
        // Tree
        float3(220.0f, 220.0f, 220.0f),
        // Truck_Bus
        float3(153.0f, 102.0f, 204.0f),
        // Tunnel
        float3(238.0f, 130.0f, 238.0f),
        // VegetationMisc
        float3(0.0f, 128.0f, 128.0f),
        // Void
        float3(255.0f, 192.0f, 203.0f),
        // Wall
        float3(160.0f, 82.0f, 45.0f)
    };
 

    // Get the label index from the red color channel
    int index = (int)MaskTexture[id.xy].r;

    // Get the mask color value for the current pixel
    float4 maskColor = float4(
        colors[index].r / 255.0f,
        colors[index].g / 255.0f,
        colors[index].b / 255.0f,
        1.0f
        );

    // Set the pixel color values for the processed image
    Result[id.xy] = maskColor * maskWeight + (1 - maskWeight) * SourceImage[id.xy];
}